FROM node:lts AS runtime
WORKDIR /app

COPY . .

ARG DB_URL=${DB_URL}
ENV DB_URL=${DB_URL}

ARG SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}

ARG EMAIL_TO=${EMAIL_TO}
ENV EMAIL_TO=${EMAIL_TO}

ARG EMAIL_FROM=${EMAIL_FROM}
ENV EMAIL_FROM=${EMAIL_FROM}

RUN npm install
RUN npm run build

RUN npm run migrate:push

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs